version: '3'
services:
  nginx: 
    build: ./nginx
    # image: upscale/nginx
    container_name: nginx
    ports:
      - 80:80

  nodejs: 
    build: ./
    # image: upscale/nodejs
    container_name: apps
    # ports:
    #   - 3000:3000
